# Generated by Django 6.0.7 on 2026-07-14 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=10)),
                ("region", models.CharField(max_length=50)),
                (
                    "commission_share",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "monthly_target",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=10)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("walkin", "Walkin"),
                        ],
                        max_length=12,
                    ),
                ),
                ("interested_property_type", models.CharField(max_length=255)),
                ("min_budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_budget", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("site_visited", "Site Visited"),
                            ("negotiations", "Negotiations"),
                            ("lost", "Lost"),
                            ("done", "Done"),
                        ],
                        max_length=16,
                    ),
                ),
                ("preferred_location", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.agent"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("commercial", "Commercial"),
                            ("plot", "Plot"),
                        ],
                        max_length=12,
                    ),
                ),
                ("images", models.ImageField(upload_to="properties")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("sold", "Sold")],
                        max_length=12,
                    ),
                ),
                ("area_sqft", models.PositiveIntegerField()),
                ("listed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.agent"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending"),
                            ("done", "Done"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expected_closing_date", models.DateField()),
                ("actual_closing_date", models.DateField()),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.lead"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.property"
                    ),
                ),
            ],
        ),
    ]
