# Generated by Django 6.0.7 on 2026-07-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="interested_property_type",
            new_name="interested_property_types",
        ),
    ]
