# Generated by Django 6.0.7 on 2026-07-14 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_interested_property_type_lead_interested_property_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="lead",
            name="max_budget",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="lead",
            name="min_budget",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="property",
            name="listing_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.agent",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("available", "Available"), ("sold", "Sold")],
                max_length=12,
            ),
        ),
    ]
