# Generated by Django 6.0.7 on 2026-07-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_deal_amount_alter_lead_max_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("sold", "Sold")],
                default="available",
                max_length=12,
            ),
        ),
    ]
