# Generated by Django 6.0.7 on 2026-07-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_property_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="status",
            field=models.CharField(
                choices=[
                    ("cancelled", "Cancelled"),
                    ("pending", "Pending"),
                    ("done", "Done"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
