# Generated by Django 5.2.10 on 2026-07-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_deal_actual_closing_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="images",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="agent",
            name="monthly_target",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
