# Generated by Django 5.2.10 on 2026-07-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_images_property_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="profile_photo",
            field=models.ImageField(
                default="profiles/default.jpg", upload_to="profiles"
            ),
        ),
    ]
