# Generated by Django 5.2.10 on 2026-07-15 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_agent_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
