# Generated by Django 5.2.10 on 2026-07-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_agent_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="Description",
            new_name="description",
        ),
    ]
