# Generated by Django 5.2.10 on 2026-07-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rename_description_property_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="listing_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="core.agent",
            ),
        ),
    ]
